# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bk_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
                ('protect', models.CharField(max_length=10)),
                ('plan', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='bk_policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=20)),
                ('client', models.CharField(max_length=20, verbose_name='bak host')),
                ('trees', models.CharField(max_length=200, verbose_name='bak dir')),
                ('drive', models.CharField(max_length=20)),
                ('da', models.CharField(max_length=20)),
                ('script', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='bk_plan',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dp.bk_policy'),
        ),
    ]
